/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  banner: () => import("@/views/banner/index.vue"),
  cooperation_config: () => import("@/views/cooperation/config/index.vue"),
  cooperation_image: () => import("@/views/cooperation/image/index.vue"),
  example_body_config: () => import("@/views/example/body/config/index.vue"),
  example_body_image: () => import("@/views/example/body/image/index.vue"),
  example_cover_config: () => import("@/views/example/cover/config/index.vue"),
  example_cover_image: () => import("@/views/example/cover/image/index.vue"),
  feature: () => import("@/views/feature/index.vue"),
  footer: () => import("@/views/footer/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_multi-tab": () => import("@/views/function/multi-tab/index.vue"),
  function_tab: () => import("@/views/function/tab/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  masonry_salon: () => import("@/views/masonry/salon/index.vue"),
  masonry_scholar: () => import("@/views/masonry/scholar/index.vue"),
  process_config: () => import("@/views/process/config/index.vue"),
  process_image: () => import("@/views/process/image/index.vue"),
  sample_config: () => import("@/views/sample/config/index.vue"),
  sample_image: () => import("@/views/sample/image/index.vue"),
  spotlight: () => import("@/views/spotlight/index.vue"),
  standpoint_config: () => import("@/views/standpoint/config/index.vue"),
  standpoint_image: () => import("@/views/standpoint/image/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  visualization_config: () => import("@/views/visualization/config/index.vue"),
  visualization_image: () => import("@/views/visualization/image/index.vue"),
};
