/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 110
    }
  },
  {
    name: 'banner',
    path: '/banner',
    component: 'layout.base$view.banner',
    meta: {
      title: 'banner',
      i18nKey: 'route.banner',
      icon: 'material-symbols:planner-banner-ad-pt-outline',
      order: 2
    }
  },
  {
    name: 'cooperation',
    path: '/cooperation',
    component: 'layout.base',
    meta: {
      title: 'cooperation',
      i18nKey: 'route.cooperation',
      icon: 'ri:team-line',
      order: 3
    },
    children: [
      {
        name: 'cooperation_config',
        path: '/cooperation/config',
        component: 'view.cooperation_config',
        meta: {
          title: 'cooperation_config',
          i18nKey: 'route.cooperation_config',
          icon: 'icon-park-twotone:config'
        }
      },
      {
        name: 'cooperation_image',
        path: '/cooperation/image',
        component: 'view.cooperation_image',
        meta: {
          title: 'cooperation_image',
          i18nKey: 'route.cooperation_image',
          icon: 'uim:image-v'
        }
      }
    ]
  },
  {
    name: 'example',
    path: '/example',
    component: 'layout.base',
    meta: {
      title: 'example',
      i18nKey: 'route.example',
      icon: 'fluent:tray-item-add-20-filled',
      order: 4
    },
    children: [
      {
        name: 'example_body',
        path: '/example/body',
        meta: {
          title: 'example_body',
          i18nKey: 'route.example_body',
          icon: 'fluent:code-text-20-filled'
        },
        children: [
          {
            name: 'example_body_config',
            path: '/example/body/config',
            component: 'view.example_body_config',
            meta: {
              title: 'example_body_config',
              i18nKey: 'route.example_body_config',
              icon: 'icon-park-twotone:config'
            }
          },
          {
            name: 'example_body_image',
            path: '/example/body/image',
            component: 'view.example_body_image',
            meta: {
              title: 'example_body_image',
              i18nKey: 'route.example_body_image',
              icon: 'uim:image-v'
            }
          }
        ]
      },
      {
        name: 'example_cover',
        path: '/example/cover',
        meta: {
          title: 'example_cover',
          i18nKey: 'route.example_cover',
          icon: 'material-symbols:full-coverage-outline'
        },
        children: [
          {
            name: 'example_cover_config',
            path: '/example/cover/config',
            component: 'view.example_cover_config',
            meta: {
              title: 'example_cover_config',
              i18nKey: 'route.example_cover_config',
              icon: 'icon-park-twotone:config'
            }
          },
          {
            name: 'example_cover_image',
            path: '/example/cover/image',
            component: 'view.example_cover_image',
            meta: {
              title: 'example_cover_image',
              i18nKey: 'route.example_cover_image',
              icon: 'uim:image-v'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'feature',
    path: '/feature',
    component: 'layout.base$view.feature',
    meta: {
      title: 'feature',
      i18nKey: 'route.feature',
      icon: 'material-symbols:star-outline',
      order: 5
    }
  },
  {
    name: 'footer',
    path: '/footer',
    component: 'layout.base$view.footer',
    meta: {
      title: 'footer',
      i18nKey: 'route.footer',
      icon: 'fluent:document-footer-24-filled',
      order: 6
    }
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 116
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child',
          icon: 'material-symbols:filter-list-off'
        },
        redirect: '/function/hide-child/one',
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one',
              icon: 'material-symbols:filter-list-off',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab',
          icon: 'ic:round-tab',
          multiTab: true,
          hideInMenu: true,
          activeMenu: 'function_tab'
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab',
          icon: 'ic:round-tab'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 119,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'masonry',
    path: '/masonry',
    component: 'layout.base',
    meta: {
      title: 'masonry',
      i18nKey: 'route.masonry',
      icon: 'fluent:data-waterfall-20-filled',
      order: 7
    },
    children: [
      {
        name: 'masonry_salon',
        path: '/masonry/salon',
        component: 'view.masonry_salon',
        meta: {
          title: 'masonry_salon',
          i18nKey: 'route.masonry_salon',
          icon: 'map:beauty-salon'
        }
      },
      {
        name: 'masonry_scholar',
        path: '/masonry/scholar',
        component: 'view.masonry_scholar',
        meta: {
          title: 'masonry_scholar',
          i18nKey: 'route.masonry_scholar',
          icon: 'mdi:university'
        }
      }
    ]
  },
  {
    name: 'process',
    path: '/process',
    component: 'layout.base',
    meta: {
      title: 'process',
      i18nKey: 'route.process',
      icon: 'mingcute:process-fill',
      order: 8
    },
    children: [
      {
        name: 'process_config',
        path: '/process/config',
        component: 'view.process_config',
        meta: {
          title: 'process_config',
          i18nKey: 'route.process_config',
          icon: 'icon-park-twotone:config'
        }
      },
      {
        name: 'process_image',
        path: '/process/image',
        component: 'view.process_image',
        meta: {
          title: 'process_image',
          i18nKey: 'route.process_image',
          icon: 'uim:image-v'
        }
      }
    ]
  },
  {
    name: 'sample',
    path: '/sample',
    component: 'layout.base',
    meta: {
      title: 'sample',
      i18nKey: 'route.sample',
      icon: 'ri:align-item-top-line',
      order: 9
    },
    children: [
      {
        name: 'sample_config',
        path: '/sample/config',
        component: 'view.sample_config',
        meta: {
          title: 'sample_config',
          i18nKey: 'route.sample_config',
          icon: 'icon-park-twotone:config'
        }
      },
      {
        name: 'sample_image',
        path: '/sample/image',
        component: 'view.sample_image',
        meta: {
          title: 'sample_image',
          i18nKey: 'route.sample_image',
          icon: 'uim:image-v'
        }
      }
    ]
  },
  {
    name: 'spotlight',
    path: '/spotlight',
    component: 'layout.base$view.spotlight',
    meta: {
      title: 'spotlight',
      i18nKey: 'route.spotlight',
      icon: 'mdi:spotlight-beam',
      order: 10
    }
  },
  {
    name: 'standpoint',
    path: '/standpoint',
    component: 'layout.base',
    meta: {
      title: 'standpoint',
      i18nKey: 'route.standpoint',
      icon: 'icon-park-outline:six-points',
      order: 11
    },
    children: [
      {
        name: 'standpoint_config',
        path: '/standpoint/config',
        component: 'view.standpoint_config',
        meta: {
          title: 'standpoint_config',
          i18nKey: 'route.standpoint_config',
          icon: 'icon-park-twotone:config'
        }
      },
      {
        name: 'standpoint_image',
        path: '/standpoint/image',
        component: 'view.standpoint_image',
        meta: {
          title: 'standpoint_image',
          i18nKey: 'route.standpoint_image',
          icon: 'uim:image-v'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  },
  {
    name: 'visualization',
    path: '/visualization',
    component: 'layout.base',
    meta: {
      title: 'visualization',
      i18nKey: 'route.visualization',
      icon: 'fluent:search-visual-24-filled',
      order: 12
    },
    children: [
      {
        name: 'visualization_config',
        path: '/visualization/config',
        component: 'view.visualization_config',
        meta: {
          title: 'visualization_config',
          i18nKey: 'route.visualization_config',
          icon: 'icon-park-twotone:config'
        }
      },
      {
        name: 'visualization_image',
        path: '/visualization/image',
        component: 'view.visualization_image',
        meta: {
          title: 'visualization_image',
          i18nKey: 'route.visualization_image',
          icon: 'uim:image-v'
        }
      }
    ]
  }
];
